# Generated by Django 4.1.2 on 2022-10-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='attraction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attractions.attraction'),
        ),
    ]
