# Generated by Django 4.1.2 on 2022-10-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_alter_favorite_attraction_alter_favorite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='attraction',
            field=models.CharField(max_length=100),
        ),
    ]
